version: '3'

services:
  db:
      image: mysql
      container_name: db_docker_symfony
      restart: always
      ports:
          - 3306:3306
      volumes:
          - db-data:/var/lib/mysql
      environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      networks:
        - tech-test
  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin_docker_symfony
      restart: always
      depends_on:
          - db
      ports:
          - 8085:80
      environment:
          PMA_HOST: db
      networks:
        - tech-test
  rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypassword
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
        networks:
        - tech-test
  app:
      build: app
      container_name: www_docker_symfony
      ports:
        - "8741:80"
      volumes:
          - ./app/vhosts:/etc/apache2/sites-enabled
          - ./:/var/www
      restart: always
      depends_on:
          - db
      networks:
            - tech-test

volumes:
  db-data:

networks:
  tech-test:
